version: "3"

services:
  grafana:
    image: grafana/grafana:5.3.0
    container_name: grafana
    environment:
        - GF_SERVER_ROOT_URL=http://192.168.99.101
        - GF_SECURITY_ADMIN_PASSWORD=123456
    ports:
        - 3000:3000
    user: "104"
  database:
    image: postgres:9.5
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=grafana
      - POSTGRES_PASSWORD=grafana
      - POSTGRES_DB=postgres
  pgadmin:
    image: dpage/pgadmin4:4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=grafana
      - PGADMIN_DEFAULT_PASSWORD=123456
    expose:
      - "80"
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin:/root/.pgadmin
    labels:
      - "traefik.backend=naturalis-pgadmin"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.port=80"
      - ${GRAFANA_URL_CONFIG:-traefik.frontend.rule=Host:pgadmin.docker.localhost}
#     - ${GRAFANA_URL_CONFIG:-traefik.frontend.rule=Host:pgadmin.naturalis.nl}
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    environment:
      - EUREKA_SERVICE_URI=http://192.168.99.101:8761
      - POSTGRES_SERVICE_URI=http://192.168.99.101:5432
    depends_on:
      - eurekaserver
  node_exporter:
    image: 'quay.io/prometheus/node-exporter'
    container_name: node_exporter
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
  kafkaserver:
    image: spotify/kafka
    container_name: kafka
    ports:
      - 2181:2181
      - 9092:9092
  eurekaserver:
   image:   johncarnell/tmx-eurekasvr:chapter8
   container_name: eurekaserver
   ports:
       - "8761:8761"
  configserver:
    image: johncarnell/tmx-confsvr:chapter8
    container_name: configserver
    ports:
       - "8888:8888"
    environment:
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
       EUREKASERVER_PORT: "8761"
       ENCRYPT_KEY:       "IMSYMMETRIC"
  zuulserver:
    image: johncarnell/tmx-zuulsvr:chapter8
    container_name: zuulserver
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"