version: "3"

services:
  grafana:
    image: grafana/grafana:5.1.0
    container_name: grafana
    environment:
        - GF_SERVER_ROOT_URL=http://192.168.99.101
        - GF_SECURITY_ADMIN_PASSWORD=123456
    ports:
        - 3000:3000
    user: "104"
  mysql:
    image: mysql:5.7
    ports: 
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: fiapdb
        MYSQL_USER: fiap
        MYSQL_PASSWORD: 123456
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  kafkaserver:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
  eurekaserver:
   image:   johncarnell/tmx-eurekasvr:chapter8
   ports:
       - "8761:8761"
  configserver:
    image: johncarnell/tmx-confsvr:chapter8
    ports:
       - "8888:8888"
    environment:
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
       EUREKASERVER_PORT: "8761"
       ENCRYPT_KEY:       "IMSYMMETRIC"
  zuulserver:
    image: johncarnell/tmx-zuulsvr:chapter8
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr@s
      - POSTGRES_DB=postgres
  